const S=window.V42, C=window.V42_COMP;
const $=id=>document.getElementById(id), pos=$('position'), scoring=$('scoring');
let expanded=false;
const DDEF={fr:2,td:6,ff:2,int:2,sack:2,safety:2,p0:10,p6:7,p13:4,p21:1,p27:-1,p34:-4,p45:-7,p46:-10,ym:'off',y99:0,y199:0,y299:0,y349:0,y399:0,y449:0,y499:0,y549:0,y550:0};
const KDEF={fg019:3,fg2029:3,fg3039:3,fg4049:4,fg5059:5,fg60:5,m019:0,m2029:0,m3039:0,m4049:0,m5059:0,m60:0,xp:1,xpm:0};
let dRules={...DDEF},kRules={...KDEF};
const DE=[['fr','Fumble Recovered (DFR)'],['td','Defensive / ST TD'],['ff','Forced Fumble'],['int','Interception'],['sack','Sack'],['safety','Safety']];
const PA=[['p0','PA: 0'],['p6','PA: 1–6'],['p13','PA: 7–13'],['p21','PA: 14–21'],['p27','PA: 22–27'],['p34','PA: 28–34'],['p45','PA: 35–45'],['p46','PA: 46+']];
const YA=[['y99','YA: 0–99'],['y199','YA: 100–199'],['y299','YA: 200–299'],['y349','YA: 300–349'],['y399','YA: 350–399'],['y449','YA: 400–449'],['y499','YA: 450–499'],['y549','YA: 500–549'],['y550','YA: 550+']];
const KF=[['fg019','FG made 0–19'],['fg2029','FG made 20–29'],['fg3039','FG made 30–39'],['fg4049','FG made 40–49'],['fg5059','FG made 50–59'],['fg60','FG made 60+'],['m019','Miss 0–19'],['m2029','Miss 20–29'],['m3039','Miss 30–39'],['m4049','Miss 40–49'],['m5059','Miss 50–59'],['m60','Miss 60+'],['xp','XP made'],['xpm','XP missed']];
function rng(seed){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
const R=rng(C.seed);
function norm(){let u=Math.max(R(),1e-12),v=R();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function pois(l){if(l<=0)return 0;if(l<10){let L=Math.exp(-l),p=1,k=0;do{k++;p*=R()}while(p>L);return k-1}return Math.max(0,Math.round(l+Math.sqrt(l)*norm()))}
function bin(n,p){let x=0;for(let j=0;j<n;j++)if(R()<p)x++;return x}
const DRAWD=C.d.map(r=>{let out=[];for(let s=0;s<C.n;s++)out.push([pois(r[4]),pois(r[5]),pois(r[6]),pois(r[7]),pois(r[8]),pois(r[9]),pois(r[10]),pois(r[11]),Math.max(0,r[12]+8.8*norm()),Math.max(0,r[13]+74*norm())]);return out});
const DRAWK=C.k.map(r=>{let out=[],pa=r[6],pr=pa?Math.min(1,r[7]/pa):.95,att=r.slice(8,14),made=r.slice(14,20),mr=att.map((a,j)=>a?Math.min(1,made[j]/a):.8);for(let s=0;s<C.n;s++){let pat=pois(pa),pm=bin(pat,pr),aa=[],mm=[];for(let b=0;b<6;b++){let a=pois(att[b]),m=bin(a,mr[b]);aa.push(a);mm.push(m)}out.push([pat,pm,...aa,...mm])}return out});
function pct(x){return`${(100*x).toFixed(1)}%`} function sgn(x){return`${x>0?'+':''}${Number(x).toFixed(1)}`}
function field(box,k,l,v){let w=document.createElement('label');w.textContent=l;let i=document.createElement('input');i.type='number';i.step='.1';i.value=v;i.dataset.k=k;w.appendChild(i);box.appendChild(w)}
function opts(){scoring.innerHTML='';(pos.value==='dst'?[['n','No yards allowed'],['y','With yards allowed'],['c','Custom D/ST']]:[['b','Bucket'],['d','Decimal'],['c','Custom kicker']]).forEach(([v,t])=>{let o=document.createElement('option');o.value=v;o.textContent=t;scoring.appendChild(o)})}
function customUI(){let box=$('custom');box.innerHTML='';box.classList.toggle('on',scoring.value==='c');if(scoring.value!=='c')return;if(pos.value==='dst'){box.innerHTML='<div class="sectionlabel">Defensive / Special Teams</div><div class="fieldgrid" id="de"></div><div class="sectionlabel">Points Allowed</div><div class="fieldgrid" id="pa"></div><div class="sectionlabel">Yards Allowed</div><label>Mode<select id="ym"><option value="off">Disabled / 0 points</option><option value="tiers">Use custom tiers</option></select></label><div class="fieldgrid" id="ya"></div><div style="margin-top:12px"><button class="primary" id="apply">Apply scoring</button> <button id="reset">Reset</button></div>';DE.forEach(x=>field($('de'),x[0],x[1],dRules[x[0]]));PA.forEach(x=>field($('pa'),x[0],x[1],dRules[x[0]]));YA.forEach(x=>field($('ya'),x[0],x[1],dRules[x[0]]));$('ym').value=dRules.ym}else{box.innerHTML='<div class="sectionlabel">Kicker Custom Scoring</div><div class="fieldgrid" id="kf"></div><div style="margin-top:12px"><button class="primary" id="apply">Apply scoring</button> <button id="reset">Reset</button></div>';KF.forEach(x=>field($('kf'),x[0],x[1],kRules[x[0]]))}$('apply').onclick=()=>{if(pos.value==='dst'){document.querySelectorAll('#custom input').forEach(i=>dRules[i.dataset.k]=+i.value||0);dRules.ym=$('ym').value}else document.querySelectorAll('#custom input').forEach(i=>kRules[i.dataset.k]=+i.value||0);render()};$('reset').onclick=()=>{if(pos.value==='dst')dRules={...DDEF};else kRules={...KDEF};customUI();render()}}
function band(x,a){for(const [m,v] of a)if(x<=m)return v;return 0}
function summary(meta,draws,isK){let n=meta.length,ns=draws[0].length,t5=[],t10=[];for(let s=0;s<ns;s++){let v=draws.map(a=>a[s]).sort((a,b)=>b-a);t5[s]=v[4];t10[s]=v[9]}let out=meta.map((m,i)=>{let a=draws[i],sum=0,g=0,p5=0,p10=0;for(let s=0;s<ns;s++){sum+=a[s];if(a[s]>=10)g++;if(a[s]>=t5[s])p5++;if(a[s]>=t10[s])p10++}return isK?[m[0],m[1],m[2],m[3],m[4],sum/ns,g/ns,p5/ns,p10/ns,m[5]]:[m[0],m[1],m[2],m[3],sum/ns,g/ns,p5/ns,p10/ns]});return out.sort((a,b)=>(isK?b[5]-a[5]:b[4]-a[4]))}
function cDst(){let pa=[[0,dRules.p0],[6,dRules.p6],[13,dRules.p13],[21,dRules.p21],[27,dRules.p27],[34,dRules.p34],[45,dRules.p45],[1e9,dRules.p46]],ya=[[99,dRules.y99],[199,dRules.y199],[299,dRules.y299],[349,dRules.y349],[399,dRules.y399],[449,dRules.y449],[499,dRules.y499],[549,dRules.y549],[1e9,dRules.y550]],scores=DRAWD.map(a=>a.map(x=>x[0]*dRules.sack+x[1]*dRules.int+x[2]*dRules.fr+x[3]*dRules.ff+x[4]*dRules.safety+(x[6]+x[7])*dRules.td+band(x[8],pa)+(dRules.ym==='tiers'?band(x[9],ya):0)));return summary(C.d.map(r=>r.slice(0,4)),scores,false)}
function cK(){let mk=[kRules.fg019,kRules.fg2029,kRules.fg3039,kRules.fg4049,kRules.fg5059,kRules.fg60],ms=[kRules.m019,kRules.m2029,kRules.m3039,kRules.m4049,kRules.m5059,kRules.m60],scores=DRAWK.map(a=>a.map(x=>{let v=x[1]*kRules.xp+(x[0]-x[1])*kRules.xpm;for(let b=0;b<6;b++){let at=x[2+b],md=x[8+b];v+=md*mk[b]+(at-md)*ms[b]}return v}));return summary(C.k.map(r=>r.slice(0,6)),scores,true)}
function rows(){if(pos.value==='dst')return scoring.value==='n'?S.dn:scoring.value==='y'?S.dy:cDst();return scoring.value==='b'?S.kb:scoring.value==='d'?S.kd:cK()}
function render(){let r=rows(),d=pos.value==='dst',show=expanded?r:r.slice(0,10);$('loading').hidden=true;$('table').hidden=false;$('thead').innerHTML='<tr>'+(d?['Rk','D/ST','Opp','Proj','P(10+)','P(Top 5)','P(Top 10)','Spread','Total']:['Rk','Kicker','Team','Opp','Proj','P(10+)','P(Top 5)','P(Top 10)','Spread','Total']).map(x=>`<th>${x}</th>`).join('')+'</tr>';$('tbody').innerHTML='';show.forEach((x,i)=>{let tr=document.createElement('tr');if(d)tr.innerHTML=`<td class="rank">${i+1}</td><td class="name">${x[0]}</td><td>${x[1]}</td><td>${x[4].toFixed(2)}</td><td>${pct(x[5])}</td><td>${pct(x[6])}</td><td>${pct(x[7])}</td><td>${sgn(x[2])}</td><td>${x[3].toFixed(1)}</td>`;else tr.innerHTML=`<td class="rank">${i+1}</td><td class="name">${x[0]}${x[9]?'<span class="competition">JOB BATTLE</span>':''}</td><td>${x[1]}</td><td>${x[2]}</td><td>${x[5].toFixed(2)}</td><td>${pct(x[6])}</td><td>${pct(x[7])}</td><td>${pct(x[8])}</td><td>${sgn(x[3])}</td><td>${x[4].toFixed(1)}</td>`;$('tbody').appendChild(tr)});let q=r[0],p=d?4:5;$('leader').textContent=q[0];$('leaderProj').textContent=q[p].toFixed(2);$('leaderTop5').textContent=pct(q[p+2]);$('leaderTop10').textContent=pct(q[p+3]);$('showing').textContent=expanded?'Showing all 32':'Showing top 10 of 32';$('toggleAll').textContent=expanded?'Show top 10':'Show all 32';$('lastUpdated').textContent=`Last updated ${S.updated}`;$('updatedBadge').textContent=`Updated ${S.updated}`;$('note').textContent=scoring.value==='c'?'Custom scoring re-scores the saved current v4.2 forecast state.':'v4.2 Week 1 model snapshot.'}
pos.onchange=()=>{expanded=false;opts();customUI();render()};scoring.onchange=()=>{expanded=false;customUI();render()};$('toggleAll').onclick=()=>{expanded=!expanded;render()};
async function refreshModel(){
 const btn=$('refreshPage'),endpoint=(window.V42_REFRESH_ENDPOINT||'').replace(/\/$/,'');
 if(!endpoint){alert('Automated refresh is not connected yet. Deploy the Cloudflare Worker and set its URL in config.js.');return;}
 let pin=localStorage.getItem('v42_refresh_pin')||prompt('Enter your refresh PIN');if(!pin)return;localStorage.setItem('v42_refresh_pin',pin);
 const original=btn.textContent;btn.disabled=true;btn.textContent='Starting refresh…';
 try{
  let r=await fetch(endpoint+'/refresh',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pin})});
  if(r.status===401){localStorage.removeItem('v42_refresh_pin');throw new Error('Incorrect refresh PIN. Click again to retry.');}
  if(!r.ok)throw new Error('Refresh gateway returned '+r.status);
  let x=await r.json(),run=x.run_id;btn.textContent=x.reused?'Refresh already running…':'Running v4.2…';const start=Date.now();
  while(Date.now()-start<12*60*1000){await new Promise(z=>setTimeout(z,5000));let q=await fetch(endpoint+'/status'+(run?'?run_id='+encodeURIComponent(run):''),{cache:'no-store'});if(!q.ok)continue;let st=await q.json();if(st.run_id)run=st.run_id;if(st.status==='queued')btn.textContent='Refresh queued…';else if(st.status==='in_progress')btn.textContent='Running v4.2…';else if(st.status==='completed'){if(st.conclusion!=='success')throw new Error('Model refresh finished with '+(st.conclusion||'an error'));btn.textContent='Publishing rankings…';await new Promise(z=>setTimeout(z,18000));location.reload();return;}}
  throw new Error('Refresh is still running. Reload the page in a few minutes.');
 }catch(e){alert(e.message||String(e));btn.disabled=false;btn.textContent=original;}
}
$('refreshPage').onclick=refreshModel;opts();customUI();render();
